# Generated by Django 2.0.13 on 2020-12-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201221_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Guest email address'),
        ),
    ]
