# Generated by Django 2.2.3 on 2021-02-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20210220_1740'),
        ('offer', '0007_conditionaloffer_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='included_partners',
            field=models.ManyToManyField(blank=True, related_name='partnerincludes', to='partner.Partner', verbose_name='Included Partners'),
        ),
    ]
