# Generated by Django 2.0.13 on 2020-12-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170821_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='details',
            field=models.TextField(blank=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, verbose_name='Details'),
        ),
    ]
