# Generated by Django 2.2.13 on 2021-03-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20201211_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='required',
            field=models.BooleanField(null=True, verbose_name='Required'),
        ),
    ]
