# Generated by Django 2.2.13 on 2021-04-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20210311_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='gst',
            field=models.FloatField(editable=False, null=True, verbose_name='Rating'),
        ),
    ]
