# Generated by Django 2.2.13 on 2021-04-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20210428_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='gst',
        ),
        migrations.AddField(
            model_name='category',
            name='gst',
            field=models.FloatField(editable=False, null=True, verbose_name='GST'),
        ),
    ]
