# Generated by Django 2.2.3 on 2021-02-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20160107_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecord',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='price_retail',
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='jr_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='JR usable credit'),
        ),
    ]
