# Generated by Django 2.2.3 on 2021-02-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20210218_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='partner.Partner', verbose_name='Admin'),
        ),
    ]
