# Generated by Django 2.2.3 on 2021-02-20 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_partner_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
    ]
