# Generated by Django 2.2.13 on 2021-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20210220_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='jr_credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='JR usable credit'),
        ),
    ]
