# Generated by Django 2.2.3 on 2021-02-26 12:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20160323_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='credit_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Credit Used'),
        ),
    ]
